name: eTravelLand
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50196
title: 'eTravelLand '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#babbb6'
    - '#83775f'
    - '#a12e02'
    - '#2f2b25'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
