name: eTravelLand
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50196
title: 'eTravelLand '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009cfd'
    - '#fefefd'
    - '#504d00'
    - '#e8c901'
    - '#db3100'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
