name: eTravelLand
favicon: null
layout_spectrum: 0.4819148110691458
typography_spectrum: 0.05190149275586009
title: 'eTravelLand '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5625
  lightness: 0.36089937039650977
  saturation: 0.5625
  rhythmicContrast: 0.03404534584842622
purpose: []
